fail_fast: true

repos:
-   repo: https://github.com/psf/black
    rev: 21.4b0
    hooks:
    -   id: black
        name: "Black format checker"
        args: ["--check"]
        language_version: python3

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.901
    hooks:
    -   id: mypy
        name: "Python types analyzer"
        args: ["--allow-redefinition", "--ignore-missing-imports", "--cache-dir=/dev/null", "src"]
        language: python
        pass_filenames: false
