name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:

  check:
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v2
    - name: "Set up Python 3.6"
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: "Set up private packages SSH keys"
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: |
          ${{ secrets.DM_CORE_SSH_KEY }}
    - name: "Install Python dependencies"
      run: |
        pip install --no-cache-dir --upgrade pip setuptools wheel
        pip install --no-cache-dir --requirement requirements.txt
        pip install --no-cache-dir --requirement requirements-dev.txt
        pip list
    - name: "Check code format"
      run: |
        make check

  build:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v2
    - name: "Set up private packages SSH keys"
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: |
          ${{ secrets.DM_CORE_SSH_KEY }}
    - name: "Build Docker image"
      run: |
        make build
