name: Continuous Integration


on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  lint:
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v3
    - name: "Set up Python"
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: "Set up private packages SSH keys"
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: |
          ${{ secrets.DM_CORE_SSH_KEY }}
          ${{ secrets.DM_SCHEMAS_SSH_KEY }}
    - name: "Install Python dependencies"
      run: |
        pip install --no-cache-dir --upgrade pip setuptools wheel
        pip install --no-cache-dir --requirement reqs/requirements-prod.txt
        pip install --no-cache-dir --requirement reqs/requirements-lint.txt
        pip list
    - name: "Check format"
      run: |
        make check

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v3
    - name: "Set up Python"
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: "Set up private packages SSH keys"
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: |
          ${{ secrets.DM_CORE_SSH_KEY }}
          ${{ secrets.DM_SCHEMAS_SSH_KEY }}
    - name: "Install Python dependencies"
      run: |
        pip install --no-cache-dir --upgrade pip setuptools wheel
        pip install --no-cache-dir --requirement reqs/requirements-prod.txt
        pip install --no-cache-dir --requirement reqs/requirements-spec.txt
        pip install --no-cache-dir --requirement reqs/requirements-test.txt
        pip list
    - name: "Run tests"
      run: |
        make test

#  ONLY POSSIBLE WHEN PROJECT GOES PUBLIC
#
#  build:
#    needs: [test]
#    runs-on: ubuntu-latest
#    steps:
#    - name: "Set up GitHub Actions"
#      uses: actions/checkout@v3
#    - name: "Set up private packages SSH keys"
#      uses: webfactory/ssh-agent@v0.6.0
#      with:
#        ssh-private-key: |
#          ${{ secrets.DM_CORE_SSH_KEY }}
#          ${{ secrets.DM_SCHEMAS_SSH_KEY }}
#    - name: "Build Docker image"
#      run: |
#        make build
